name: Trigger rebuild

on: push

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build on dockerhub
        env:
          DOCKER_USERNAME: "nikschavan"
          DOCKER_PASSWORD: ${{ secrets.DockerPassword }}
        run: |
          bash ${GITHUB_WORKSPACE}/bin/build-images.sh
